version: '3.8'

services:
  app:
    image: python:3.9
    container_name: screenshot_app
    build:
      context: .  # 현재 디렉토리를 컨텍스트로 사용
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./images:/app/images  # 다운로드된 스크린샷을 저장할 디렉토리
    depends_on:
      - mongo  # MongoDB가 시작된 후 앱 시작

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db  # MongoDB 데이터를 유지하기 위한 볼륨
    ports:
      - "27017:27017"

volumes:
  mongo_data:
    driver: local
